#!/bin/bash
# Initialization Procdedure --- A Primordial Soup:
#      "A build-system to build the build-system that builds the build-system
#      which is a build-system that builds..."
. primalrunes/using.sh
using config
using find_program

# SECTION: MAIN
echo -e "Initializing \e[1m$PROJECT_NAME\e[22m $PROJECT_VERSION"
add_indent "   "
find_program CC gcc

