#!/bin/bash
# Initialization Procdedure --- A Primordial Soup:
#      "A build-system to build the build-system that builds the build-system
#      which is a build-system that builds..."
. primalrunes/using.sh
using module/config

using messages
using assert_dir

# SECTION: MAIN
message "Initializing \e[1m$PROJECT_NAME\e[22m $PROJECT_VERSION"
add_indent "   "

using module/perl
push_src_dir "primalrunes"
push_bin_dir "build/primalrunes"
#perl_run testbench/INC.pl
perl_test "ELF64.pm" "testbench/ELF64.pl"

